### ISSUE TITLE
Error when setting up

### ISSUE THREAD

**Issue by robertkeus** [bigcommerce/checkout-sdk-js-example#10]
I'm getting the following errors when setting up the example. Is it something I'm doing wrong?

<img width="1678" alt="screen shot 2018-08-18 at 13 56 27" src="https://user-images.githubusercontent.com/5426840/44299041-9295b100-a2ee-11e8-8863-3e52d2e28c2a.png">

**Comment by davidchin** [comment]
Hi @robertkeus, are you running the example in a theme using `stencil-cli`?

**Comment by robertkeus** [comment]
@davidchin Thanks I fixed it. I forgot the run the theme locally. 👨🏻‍💻
