### ISSUE TITLE
Broken links in Readme

### ISSUE THREAD

**Issue by richardcrichardc** [bigcommerce/checkout-sdk-js-example#14]
The link 'Integrating Checkout JS SDK Example into Cornerstone' in README.md is broken.

**Comment by richardcrichardc** [comment]
The correct link appears to be: https://developer.bigcommerce.com/stencil-docs/template-files/customize-stencil-checkout/checkout-js-sdk/implement-a-custom-checkout

**Comment by tatiana-perry** [comment]
Thanks for catching that. We will get those links updated as soon as possible. Here is a [PR](https://github.com/bigcommerce/checkout-sdk-js-example/compare/master...tatiana-perry:patch-1) you can track for now.

**Comment by TomA-R** [comment]
Thank you, the PR has been merged.
