### ISSUE TITLE
Please elaborate on production readiness of this code

### ISSUE THREAD

**Issue by TheCrawlingChaos** [bigcommerce/checkout-sdk-js-example#16]
In the documentation it says "Please note that this checkout is a good starting and reference point, but is not production ready.". 

Can you elaborate here what makes this not production ready? It could mean several things. It could mean there are rough edges that need to be ironed out by the BC team in time. It could mean there are security concerns that are not fully addressed. It could mean the UI is not handling all state changes gracefully. As someone who is trying to figure out a way to customize the checkout page, I'd appreciate as much details as I can find on this instead of a 1 line "not production ready". 

After that, if you can also elaborate in the docs, I think it will be helpful!

**Comment by emilian** [comment]
The checkout is missing a lot of functionality. For example, there are no custom address fields, no coupon codes, no gift certificates, no store credit, no terms and conditions, and no order comments. 

There is also no optimization done to the components.

**Comment by TheCrawlingChaos** [comment]
So, would it be correct to interpret the sample code as implementing a working but barebones checkout flow, as in it does not have feature parity with the existing checkout flow on BC?

**Comment by tatiana-perry** [comment]
I have submitted a PR for the readme. What is meant is you should not deploy the script in a production store. If you want to start with this then you should fork it and run your own instance.

**Comment by TheCrawlingChaos** [comment]
Got it. Thanks!
