### ISSUE TITLE
CORS error to connect GraphQL API in checkout-sdk

### ISSUE THREAD

**Issue by caglaroptimum7** [bigcommerce/checkout-sdk-js-example#25]
I am using checkout-sdk on my localhost stencil template. It was working for a long time. But suddenly I got an error about CORS like:

> 'Origin' header invalid: The 'Origin' request header value did not match the allowed origin set in the JWT auth token. Please generate a token that is valid for this origin.

My Query is:

`let myHeaders = new Headers({
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + this.props.authToken,
            "Access-Control-Allow-Origin": "http://localhost:1881",
            "Origin": "http://localhost:1881"
        });
        fetch('/graphql', {
            method: 'POST',
            headers: myHeaders,
            body: JSON.stringify({
                query: '
            query MyFirstQuery {
                  site {
                    settings {
                      storeName
                      storeHash
                      logo {
                        title
                      }
                    }
                        products (entityIds: [1270, 1269, 1273]) {
                      edges {
                        node {
                          id
                          description
                          name
                          sku
                          entityId
                          customFields {
                            edges {
                              node {
                                name
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
            '
            }),
        }).then(response => { return response.json();})
            .then((products) => {
                // Traverse the list of products which are getting from GraphQL
                products.site.data.products.edges.map((product) => {
                    product.node.customFields.edges ?
                        product.node.customFields.edges.map((line) => {
                            if (line.node.name === "ffl-firearm" && line.node.value === "1") {
                                fireArmProductIds.push(product.node.entityId);
                            }
                        }) : ""
                });
            }).catch((err)=> {
                console.log("%c Error:", "font-size: 12px; color:red;", err);
            });`

**Comment by bookernath** [comment]
Make sure you're using the latest version of stencil-cli - you can update it with `npm i -g @bigcommerce/stencil-cli`

How are you injecting your token? Do you get it from `{{settings.storefront_api.token}}`?

**Comment by caglaroptimum7** [comment]
Yes I get it from {{settings.storefront_api.token}} to react application. I use it like props.

I will update and give a feedback to you. Thanks.

**Comment by caglaroptimum7** [comment]
> Make sure you're using the latest version of stencil-cli - you can update it with `npm i -g @bigcommerce/stencil-cli`
> 
> How are you injecting your token? Do you get it from `{{settings.storefront_api.token}}`?

nope, it is now working. I updated stencil-cli.

**Comment by bookernath** [comment]
You can decode your token on https://jwt.io/ and make sure the origin in the `cors` object matches your store URL in the `.stencil` file (`cat .stencil` in your theme folder to check)

I think you should remove this from your code: `"Access-Control-Allow-Origin": "http://localhost:1881", "Origin": "http://localhost:1881" `, as I don't think it's doing anything. Those headers should be set by the browser and/or server, not by JS code.

**Comment by caglaroptimum7** [comment]
I updated "npm update @bigcommerce/checkout-sdk" and it is solved.
Thanks for your help.
