### ISSUE TITLE
How to add custom Terms and Conditions?

### ISSUE THREAD

**Issue by Fraideron** [bigcommerce/checkout-sdk-js-example#31]
I am using this repo to create the custom checkout for my store. I enabled the custom Terms and Conditions: Advanced Settings -> Checkout -> Require customers to accept terms and conditions. -> Let me type in my terms and conditions.
But, I do not know how to show "Terms and Conditions" on my checkout?

With the default checkout, all works well. But on the custom checkout, I do not know how to get this value.

**Comment by valentindellangela** [comment]
Hi @Fraideron , you can find this information under StoreConfig > OrderTermsAndConditions
See https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/checkoutstoreselector.md#getconfig and https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/checkoutsettings.md#ordertermsandconditions+ for more information.
